log_dir: tensorboard/exp/duration

out_dir:                    exp
max_train_steps:            -1
nepochs:                    200
checkpoint_epoch_interval:  30

feats_criterion: mse

stream_wise_loss:           false
use_detect_anomaly:         false

use_amp: true

optim:
  optimizer:
    name:                   RAdam
    params:
      lr:                   0.001
      betas:                [0.9, 0.999]
      weight_decay:         0.0
  lr_scheduler:
    name:                   StepLR
    params:
      step_size:            20
      gamma:                0.5

resume:
  checkpoint:
  load_optimizer:           false

cudnn:
  benchmark:                false
  deterministic:            true
