nnsvs_root:                 nnsvs
spk:                        unnamed
## exp tag(for managing experiments)
tag:                        dyvaux_notebook

out_dir:                    data

exclude_songs:              []

table_path:                 dic/DVX_jp.table
question_path:              hed/DVX_jp.hed

sample_rate:                44100

# stage 0
stage0:
    db_root:                ../singing_database

    segmentation_mode:      middle
    middle_frequency:       2

    # Choices are [strict, middle, lenient]
    vowel_duration_check:   middle

# stage 1
timelag_features:           defaults
duration_features:          defaults
acoustic_features:          static_deltadelta

trajectory_smoothing: false
trajectory_smoothing_cutoff: 50

# stage 4
acoustic_model:             acoustic_conv1dresnet
acoustic_train:             myconfig
acoustic_data:              myconfig

duration_model:             duration_lstm
duration_train:             myconfig
duration_data:              myconfig

timelag_model:              timelag_ffn
timelag_train:              myconfig
timelag_data:               myconfig

pretrained_expdir:

# stage 6
timelag_synthesis:          defaults
duration_synthesis:         defaults
acoustic_synthesis:         defaults

# latest.pth or best.pth are recommended
timelag_eval_checkpoint:    best_loss.pth
duration_eval_checkpoint:   best_loss.pth
acoustic_eval_checkpoint:   best_loss.pth

# vocoder stuff (stage 8)
vocoder_model:
pretrained_vocoder_checkpoint:
vocoder_eval_checkpoint:
